// Generated by https://quicktype.io

import { TablaAmortizacion } from "./productof.interface";
import { JsonFormValidators } from "./prueba.interface";

export interface RestAuth {
    code: number;
    name: string;
    message: string;
    data: Usuario;
    type: string;
}


export interface Usuario {
    token:       string;
    email:       string;
    nombre:      string;
    apellidos:   string;
    empresa:   string;
    perfil:      number;
    perfil_text: string;
}


export interface RestGenerales {
    code:                          number;
    name:                          string;
    "cuestionario-identificacion": CuestionarioIdentificacion[];
    documentos:                    arraydocs[];
    type:                          string;
}

export interface arraydocs {
    documento_id: number;
    documento:    string;
    file_url:     null | string;
    remplace:     number;
    create:       number;
    file_base64?: string;

}
export interface CuestionarioIdentificacion {
    groups: Group[];
}

export interface Group {
    id:    number;
    label: string;
    items: Item[];
}

export interface Item {
    id?:             number;
    label?:          string;
    formato?:        number;
    formato_text?:   string;
    tipo_dato?:      number;
    name:           string;
    value?:          string | number | null;
    validators?:     JsonFormValidators;
    value_register?:        string;
    select?:        ItemsList;
    tipo_dato_text: string;
    apply_required?: number;
    items_list?:    ItemsList[];
}
export interface ItemsList {
    id:   number;
    text: string;
}



export interface RestProductos {
    code:      number;
    name:      string;
    productos: Producto[];
    type:      string;
}

export interface Producto {
    id:     number;
    apply_iva:     number;
    clave:  string;
    nombre: string;
    marca:  string;
    modelo: string;
    serie:  string;
    precio: number;
    moneda: number;
    moneda_text:string;
}

// Generated by https://quicktype.io

export interface RestInfoLogin {
    code:           number;
    name:           string;
    token?:          string;
    empresa_logo:   string;
    empresa_nombre: string;
    empresa_color:  string;
    type:           string;
}
export interface postInfo{
    element_id: number;
    value: string;
}

// Generated by https://quicktype.io

export interface Respuesta {
    code:    number;
    solicitud_id?:    number;
    contrato?: string;
    pagare?: string;
    name:    string;
    message: string;
    type:    string;
    tabla_amortizacion:TablaAmortizacion[]
}
// Generated by https://quicktype.io

export interface RestSolicitudes {
    code:        number;
    name:        string;
    solicitudes: Solicitud[];
    type:        string;
}

export interface Solicitud {
    id:                           number;
    empresa_id:                   number;
    empresa:                      string;
    producto_id:                  number;
    producto:                     string;
    producto_financiero:                     string;
    cantidad:                     number;
    cotizacion:                   number;
    inversion_total:              number;
    descuento_valor:              number;
    importe_final:                number;
    aportacion_producto_valor:    number;
    importe_financiamiento_valor: number;
    status:                       number;
    status_text:                  string;
    registro:                     string;
    modificado:                   string;
    operador_id:                  number;
    operador:                     string;
}

// Generated by https://quicktype.io

export interface RestDetailSolicitud {
    code:             number;
    name:             string;
    solicitud_detail: SolicitudDetail;
    type:             string;
}

export interface SolicitudDetail {
    "cuestionario-identificacion": CuestionarioIdentificacion[];
    presupuesto:                   Presupuesto[];
    capacidad_id:                  Number;
    termino_credito:               TerminoCredito[];
    capacidad:                     Capacidad[];
    expediente_digital:            Expedientedigital;
    tabla_amortizacion:            TablaAmortizacion[];
}
// Generated by https://quicktype.io

export interface Expedientedigital {
    generales: arraydocs[];
    capacidad: arraydocs[];
}


export interface Capacidad {
    groups: CapacidadGroup[];
}

export interface CapacidadGroup {
    id:       number;
    label:    string;
    items: Item[];
}

export interface Concepto {
    label: string;
    items: ConceptoItem[];
}

export interface ConceptoItem {
    id:             number;
    label:          string;
    formato:        number;
    formato_text:   string;
    tipo_dato:      number;
    tipo_dato_text: string;
    formula:        string;
    nota:           string;
    apply_required: number;
    apply_calculo:  number;
    apply_captura:  number;
    default_value:  string;
    value_register: string;
}

export interface Presupuesto {
    producto:                          Producto;
    cantidad:                          number;
    moneda:                            number;
    iva:                               number;
    iva_porcentaje:                    number;
    cotizacion:                        number;
    cotizacion_total_porcentaje:       number;
    tipo_cambio:                       number;
    comision_apertura:                 number;
    comision_apertura_porcentaje:      number;
    seguro_equipo:                     number;
    inversion_total:                   number;
    precio_venta:                      number;
    precio_venta_porcentaje:           number;
    descuento_porcentaje:              number;
    descuento_valor:                   number;
    importe_final:                     number;
    aportacion_producto_porcentaje:    number;
    aportacion_producto_valor:         number;
    importe_financiamiento_porcentaje: number;
    importe_financiamiento_valor:      number;
}


export interface TerminoCredito {
    importe_credito:             number;
    plazo_credito:               number;
    taza_fija_anual:             number;
    garantias:                   string;
    forma_disposicion:           string;
    fecha_estimada_otorgamiento: string;
    forma_pago_capital_mes:      string;
    forma_pago_capital:          string;
    forma_pago_interes:          string;
    forma_pago_interes_mes:      string;
}


