// Generated by https://quicktype.io

export interface RestreporteID {
    status:  string;
    code:    number;
    message: string;
    data:    codigo;
}

export interface codigo {
    id_reporte: string;
}


export interface RestReporteNufi {
    estatus: string;
    mensaje: string;
    message?: string;
    data:    RESTReportenufiData;
    code:    number;
}

export interface RESTReportenufiData {
    ReportId:     string;
    Status:       string;
    ScoreReporte: string;
    Company:      null;
    Person:       Person;
}

export interface Person {
    Curp_Consulta:ConsultaCurp;
    RFC_Consulta:Consultarfc;
    RFC_Estatus:Estatusrfc;
    CertificadoSat_Consulta:Certificadosat;
    Siger_Consulta:Sigerconsulta;
    CedulaProfesional_Consulta:Consultacedula;
    Rug_GarantiasMobiliarias:null;
    ListasNegras_Internacionales:null;
    ContribuyentesBoletinados69B_Consulta:Listanegrasat69B;
    Ocr_Frente:                                   null;
    Ocr_Reverso:                                  null;
    ListaNominal_Consulta:                        null;
    Geolocalizacion:                              null;
    MultiBuro_ReportComplete:                     null;
    AntecedentesJudiciales_PersonaFisicaNacional:  Listanegranacional;
    SeguridadSocial_ConsultarResponse: null;
    SeguridadSocial_HistorialResponse: null;
    Infonavit_Consulta: null;
    Enriquecimiento_Datos: null;
    AnalisisYPerfilamiento_Datos: null;
    Resultados_Google: null;
    Resultados_Noticias_Google: null;
}

export interface ConsultaCurp {
    status:  string;
    message: string;
    data:    Data | null;
    code:    number;
}

export interface Data {
    gdata:    string;
    curpdata: Curpdatum[];
    files:    string[];
    guid:     string;
}

export interface Curpdatum {
    parametro:             string;
    fechaNacimiento:       string;
    docProbatorio:         number;
    segundoApellido:       string;
    curp:                  string;
    nombres:               string;
    primerApellido:        string;
    sexo:                  string;
    claveEntidad:          string;
    statusCurp:            string;
    nacionalidad:          string;
    entidad:               string;
    datosDocProbatorio:    DatosDocProbatorio;
    descriptionStatusCurp: string;
}

export interface DatosDocProbatorio {
    entidadRegistro:        string;
    tomo:                   string;
    claveMunicipioRegistro: string;
    anioReg:                string;
    claveEntidadRegistro:   string;
    foja:                   string;
    numActa:                string;
    libro:                  string;
    municipioRegistro:      string;
}


export interface Consultarfc {
    code:    number;
    status:  string;
    message: string;
    data:    Datarfc | null;
}

export interface Datarfc {
    rfc: string;
}

export interface Estatusrfc {
    status:  string;
    code:    string;
    message: string;
    data:    Dataestatus | null;
}

export interface Dataestatus {
    estatus: string;
}

export interface Certificadosat {
    status:  string;
    code:    number;
    message: string;
    data:    Datacerti | null;
}

export interface Datacerti {
    rfc:          string;
    razon_social: string;
    certificados: Certificado[];
}

export interface Certificado {
    numero_serie:  string;
    estado:        string;
    tipo:          string;
    fecha_inicial: string;
    fecha_final:   string;
    certificado:   string;
}
export interface Sigerconsulta {
    status:  string;
    code:    number;
    message: string;
    count:   number;
    data:    Datum[];
}

export interface Datum {
    fme:                   string;
    razon_social:          string;
    objeto_social:         string;
    duracion_sociedad:     string;
    domicilio_social:      string;
    nacionalidad:          string;
    estatus_fme:           string;
    rfc:                   null | string;
    numero_socios:         number;
    nombre_socios:         infosocio[];
    tipo_persona:          string;
    antecedente_registral: null | string;
    regimen_juridico:      string;
    giro:                  null | string;
    entidad_federativa:    string;
    municipio:             string;
    oficina_registral:     string;
    fecha_incripcion:      string;
    curp:                  null;
    uuid_documentos_pdf:   string;
    documentos_econtrados: any[];
}
export interface infosocio {
    estatus:string;
    nacionalidad:string;
    nombre:string;
    apellido_paterno:string;
    apellido_materno:string;
    rfc:string;
    curp:string;
    serie:string;
    fecha_constitucion:string;
    fecha_nacimiento:string;
    acciones:string;
    total:string;
    valor:string;
}
// Generated by https://quicktype.io

export interface Consultacedula {
    status:  string;
    code:    number;
    mensaje: string;
    data:    Datacedula[];
}

export interface Datacedula {
    nombre:        string;
    numCedula:     string;
    profesion:     string;
    genero:        string;
    institucion:   string;
    fechaRegistro: string;
    tipo:          string;
    estado:        string;
}

export interface Listanegrasat69B {
    status:  string;
    message: string;
    data:    null;
    code:    number;
}
// Generated by https://quicktype.io

export interface Listanegranacional {
    code:    number;
    status:  string;
    message: string;
    data:    Datanegranacional;
}

export interface Datanegranacional {
    numero_resultados: number;
    resultados:        Resultado[];
}

export interface Resultado {
    entidad:     string;
    expedientes: Expediente[];
}

export interface Expediente {
    expediente: string;
    actor:      string;
    demandado:  string;
    entidad:    string;
    juzgado:    string;
    tipo:       string;
    fuero:      string;
    fecha:      string;
    acuerdos:   Acuerdo[];
}

export interface Acuerdo {
    acuerdo: string;
    fecha:   string;
}
